name: rastro
description: "A new Flutter project."
publish_to: 'none' 


environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  json_annotation: ^4.9.0
  auto_route: ^11.1.0
  get_it: ^9.2.0
  intl: ^0.19.0
  lucide_icons: ^0.257.0
  google_sign_in: ^7.2.0
  supabase_flutter: ^2.12.0
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  json_serializable: ^6.11.3
  build_runner: ^2.10.4
  auto_route_generator: ^10.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/couriers/
    - assets/profilePhoto/
    - .env

 